### ISSUE TITLE
Dying messes up the character screen

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Equipment#102]
If a player dies, after they respawn and try to open the CharacterWindow (by pressing the "C" key by default), the stats screen shows up properly, but the slots for unequipping/equipping items don't work as intended. A player can see what items they have equipped*, but they cannot equip or unequip items. Plus, the inventory on the bottom doesn't show up. This seems to be similar to issue #3.

* They do confer stat and physical modifier benefits, but alteration effects are not applied.

**Comment by Cervator** [comment]
Hey @xrtariq2594 - think this might be obsolete? Since death has been somewhat reworked since this was submitted. I tried using the character screen after death and it seemed to work fine :-)

This was just in single player though

**Comment by jdrueckert** [comment]
This seems to have been fixed by now.
