### ISSUE TITLE
Move content to relevant submodules

### ISSUE THREAD

**Issue by syntaxi** [Terasology/Equipment#111]
As equipment currently has 130+ items across 10 tiers, its kinda bloated and not viable to be used. This suggestion is to split it up so that it can be used in actual games. This would increase the overall number of items to ~160+ but it splits them across 5 modules which comes out to an average 30 items per module.

The proposed split is as follows. (Items in **bold** don't exist and would need to be made)

# BaseEquipment

All the following items across the tiers of Wood, Copper & Iron
- *Wood*
- [ ] **WoodArms**
- [ ] **WoodLeggings**
- [ ] **WoodBoots**
- [ ] **WoodMail**
- [ ] **WoodHelmet**
- [ ] **WoodLongsword**
- [ ] WoodMace
- [ ] WoodSpear
- [ ] WoodBoStaff
- *Copper*
- [ ] **CopperArms**
- [ ] **CopperLeggings**
- [ ] **CopperBoots**
- [ ] **CopperMail**
- [ ] **CopperHelmet**
- [ ] **CopperLongsword**
- [ ] CopperMace
- [ ] CopperSpear
- [ ] CopperSabre
- *Iron*
- [ ] **IronArms**
- [ ] **IronLeggings**
- [ ] **IronBoots**
- [ ] **IronMail**
- [ ] **IronHelmet**
- [ ] IronLongsword
- [ ] IronMace
- [ ] IronSpear
- [ ] IronKeris
- [ ] IronZweihänders 

# AdditionalEquipmentTiers
This would contain the same set from Bronze, Steel, Gold and Diamond tiers
- *Bronze*
- [ ] BronzeArms
- [ ] BronzeLeggings
- [ ] BronzeBoots
- [ ] BronzeMail
- [ ] BronzeHelmet
- [ ] BronzeLongsword
- [ ] BronzeMace
- [ ] BronzeSpear
- [ ] BronzeMaul
- *Steel*
- [ ] **SteelArms**
- [ ] **SteelLeggings**
- [ ] **SteelBoots**
- [ ] **SteelMail**
- [ ] **SteelHelmet**
- [ ] SteelLongsword
- [ ] SteelMace
- [ ] SteelSpear
- [ ] SteelScimitar
- *Silver*
- [ ] **SilverArms**
- [ ] **SilverLeggings**
- [ ] **SilverBoots**
- [ ] **SilverMail**
- [ ] **SilverHelmet**
- [ ] SilverSpear
- [ ] SilverMace
- [ ] SilverLongsword
- [ ] SilverReaper
- *Gold*
- [ ] **GoldArms**
- [ ] **GoldLeggings**
- [ ] **GoldBoots**
- [ ] **GoldMail**
- [ ] **GoldHelmet**
- [ ] **GoldLongsword**
- [ ] **GoldMace**
- [ ] GoldSpear
- [ ] GoldKatana
- *Diamond*
- [ ] **DiamondArms**
- [ ] **DiamondLeggings**
- [ ] **DiamondBoots**
- [ ] **DiamondMail**
- [ ] DiamondHelmet
- [ ] DiamondLongsword
- [ ] DiamondMace
- [ ] DiamondSpear
- [ ] DiamondNunchaku

# AdditionalEquipmentItems
This would contain all the rest of the items from the tiers Wood, Copper, Bronze, Gold, Iron, Steel and Diamond

- *Copper*
- [ ] CopperAxe
- [ ] CopperMaul
- [ ] CopperRing
- *Iron*
- [ ] IronAxe
- [ ] IronDagger
- [ ] IronEspeeBastard
- [ ] IronFalchion
- [ ] IronMaul
- [ ] IronNunchaku
- [ ] IronRing
- [ ] IronScythe
- *Wood*
- [ ] WoodAxe
- [ ] WoodBoStaff
- [ ] WoodWalkingCane
- [ ] WoodMaul
- *Bronze*
- [ ] BronzeDagger
- [ ] BronzeGloves
- [ ] BronzeRing
- [ ] BronzeAxe
- *Diamond*
- [ ] DiamondAxe
- [ ] DiamondDagger
- [ ] DiamondGloves
- [ ] DiamondKatana
- [ ] DiamondMaul
- [ ] DiamondShieldArmor
- *Gold*
- [ ] 52CentsGoldChain
- [ ] GoldAxe
- [ ] GoldDagger
- [ ] GoldRing
- *Silver*
- [ ] SilverAxe
- [ ] SilverChain
- [ ] SilverDagger
- [ ] SilverMaul
- [ ] SilverPen
- [ ] SilverRing
- [ ] SilverSabre
- *Steel*
- [ ] SteelArmour
- [ ] SteelAxe
- [ ] SteelBattleAxe
- [ ] SteelDagger
- [ ] SteelDamascus
- [ ] SteelGreatsword
- [ ] SteelHatchet
- [ ] SteelKatana
- [ ] SteelMaul
- [ ] SteelRing
- [ ] SteelSword

# MagicalEquipment
All of the items from the tiers Classed and Mystic
- *Classed*
- [ ] ArchangelDagger
- [ ] ArchangelFryingPan
- [ ] ArchangelFury
- [ ] ArchangelHeart
- [ ] ArchangelSword
- [ ] CursedPendantOfLuck
- [ ] FlamingSword
- [ ] LazerSword
- [ ] LegendaryLightsaber
- *Mystic*
- [ ] MysticAxe
- [ ] BeethovensKeyFromPiano
- [ ] MysticDagger
- [ ] MysticDigger
- [ ] MysticEspeeBastard
- [ ] MysticFlowerRing
- [ ] LegendaryBrahmastra
- [ ] MysticLongsword
- [ ] MysticMace
- [ ] MysticMaul
- [ ] MysticNecklace
- [ ] MysticPendant
- [ ] MysticPendantOfEndurance
- [ ] MysticRing
- [ ] MysticSpear

# Trinkets

This would contain all the statboosting items from the tiers in AdditionalEquipmentItems
- *Copper*
- [ ] CopperLuckySword
- [ ] CopperPendant
- [ ] CopperRingOfHealing
- [ ] CopperRingOfMinorStrength
- [ ] CopperRingOfPoisonPhysicalResist
- [ ] CopperRingOfRegen
- *Iron*
- [ ] IronPendant
- [ ] IronLuckyPendant
- *Wood*
- [ ] WoodPendant
- [ ] WoodRingOfStrength
- *Bronze*
- [ ] BronzePendant
- *Steel*
- [ ] SteelPendant
- [ ] SteelBattleaxeOfAgility
- *Silver*
- [ ] SilverPendant
- *Gold*
- [ ] GoldRingOfNimbleness
- [ ] GoldRingOfSurvival
- [ ] GoldRingOfSwiftness
- [ ] GoldBadgeOfLuck
- [ ] GoldInfinity
- [ ] GoldMagicNecklace
- [ ] GoldPendant
- *Diamond*
- [ ] DiamondRingOfJuggernauts

**Comment by FieryPhoenix909** [comment]
How can these new modules be made?

**Comment by jdrueckert** [comment]
That's a very good point and will certainly be part of the module overhaul once we get past iota and other more basic modules. I'll close this issue as we'll definitely stumble over this again in the context of the module overhaul and can review it then if we need some inspiration regarding how to split the content.
