### ISSUE TITLE
New design for CharacterScreen

### ISSUE THREAD

**Issue by jasonyonathanhuang** [Terasology/Equipment#116]
![characterattributes](https://user-images.githubusercontent.com/34138344/34155948-c18bc0c2-e4ed-11e7-82c9-056379aa2bb2.jpg)

the former design of characterscreen is displaying characterattributes all at a time as a list. With this new design, i propose to make the display simpler using a dropdown selector and next/prev button. hope you'll like it :D

**Comment by mjuvekar7** [comment]
Hey so I feel you're on the right track, but I think this could be improved. Maybe in the drop down you could categorize attributes in some way?
So for example you could categorize attributes module by module. So module-specific attributes are grouped together.
So when you select the category that you want in the drop down, all attributes and values under that category are displayed below.

**Comment by jasonyonathanhuang** [comment]
![characterattributeswithquickview](https://user-images.githubusercontent.com/34138344/34185573-b551b030-e558-11e7-82cc-80a340105285.jpg)
Hi so i've got an idea to improve my UI idea. I think quickview box will make it easier to see specific data so player don't have to find their desired value from the list as they can easily find it from the quickview :D.. hope you'll like it !

**Comment by syntaxi** [comment]
I think the inclusion of the quickview helps immensely.
How will this screen be viewed? Will it appear with the inventory? Will it have it's own button?

I think I agree with mj that it should be categorised in a logical way.
These are less a part of the screen design though and something that's easier to work out when implementing it. For the fundamental design I think your idea works, although it may be a tad clunky to use that's best found by testing it.

I'll approve the task now so feel free to move onto part two if you like :)

**Comment by jdrueckert** [comment]
With the planned overall NUI and and design overhaul, we'll likely do a consistent pass over the more basic modules first, so I'll close this for now, but we can revisit it once we're higher up in the module list.
