### ISSUE TITLE
Add support for equipment pieces with stat boosts

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Equipment#4]
Right now, equipment items only confer changes to (physical) attack, (physical) defense, weight, and speed. A logical extension would be to add equipment with stat boosts. 

For example, a Copper Ring of Minor Strength boosts (physical) defense by 1, and the STR stat by 1.

We already have the PhysicalStatsModifierComponent in the PhysicalStats module. So, one way of adding this is to add the application/removal of stat boosts in the system/EquipmentSystem.java file.

**Comment by xrtariq2594** [comment]
First revision of this update is available in the [statsBoost branch](https://github.com/Terasology/Equipment/commits/statBoost).

**Comment by Cervator** [comment]
Closing as completed by #15
