### ISSUE TITLE
Add rings to each equipment "tier"

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Equipment#5]
Currently, only the Copper "tier" of equipment has a ring item. The next step would be to add rings to the Bronze, Iron, Mystic, Silver, and Steel "tiers".

To make this easier, duplicate the CopperRing prefab, modify its stats, and supply a new ring image.

**Comment by agsmith** [comment]
https://github.com/Terasology/Equipment/pull/12

**Comment by xrtariq2594** [comment]
As stated above, this issue has been solved.
