### ISSUE TITLE
Add new weapon type "spear"

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Equipment#8]
Currently, the only weapons available are longswords, axes, and daggers. A nice addition to this module would be spears.

Spears would deal around the same to less damage as longswords, have a longer range than most other melee weapons, but take longer to use.

For this, we need the following:
- Spear prefabs for each equipment tier. See prefabs for other weapons as examples.
- A spear texture for each spear.
- A spear damage prefab.

**Comment by luxcodes** [comment]
@xrtariq2594 made a pr for this

**Comment by xrtariq2594** [comment]
Good, I'll take a look at your PR (#9).

**Comment by Stefan-Mitic** [comment]
I added a wood spear to the project, would you prefer that and a stone spear or something else?

**Comment by xrtariq2594** [comment]
A wood or stone spear is fine for now @Stefan-Mitic .

**Comment by Cervator** [comment]
The wood spear by @Stefan-Mitic has been merged in (#11 / #14). Additional spear types by @HolixSF are still pending in #9
